combovis/blueprints/combo/models.py
from combovis.app import db


class Combo(db.Model):
    # Table for the combos saved by the user
    __tablename__ = 'Combo'

    cid = db.Column(db.Integer, primary_key=True)
    notation = db.Column(db.String(), unique=True, nullable=False)
    drive = db.Column(db.String(), nullable=False)
    bars = db.Column(db.String(), nullable=False)


class Favourite(db.Model):
    # Intersection table between User and Combo (many-to-many)
    __tablename__ = 'Favourite'

    fid = db.Column(db.Integer, primary_key=True)
    cid = db.Column(db.Integer, db.ForeignKey('Combo.cid'))
    uid = db.Column(db.Integer, db.ForeignKey('users.uid'))

combovis/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap5
from flask_wtf.csrf import CSRFProtect
import secrets

db = SQLAlchemy()


def create_app():
    app = Flask(__name__, template_folder='templates')
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///combovis.db'
    app.secret_key = secrets.token_urlsafe(16)

    bootstrap = Bootstrap5(app)
    csrf = CSRFProtect(app)
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'

    db.init_app(app)
    csrf.init_app(app)
    login_manager.init_app(app)

    from .blueprints.auth.models import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    from combovis.blueprints.core.routes import core
    from combovis.blueprints.combo.routes import combo
    from combovis.blueprints.auth.routes import auth_bp

    app.register_blueprint(core, url_prefix='/')
    app.register_blueprint(auth_bp, url_prefix='/auth')
    app.register_blueprint(combo, url_prefix='/combo')

    migrate = Migrate(app, db)

    return app

combovis/blueprints/combo/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from flask_login import login_required, current_user
from combovis.app import db
from .models import Combo, Favourite
import ast

from .combo_reader import convert_combo

combo = Blueprint('combo', __name__, static_folder='static', template_folder='templates')


# Route that handles combo visualization
@combo.route('/visualizer', methods=['GET', 'POST'])
def visualizer():
    if request.method == 'POST':
        form_combo = request.form.get('combo_string')
        form_combo_upper = form_combo.upper()
        converted_combo = convert_combo(form_combo_upper).split(' ')
        return render_template('combo/visualizer.html',
                               combo_str=converted_combo, raw_combo=form_combo)
    else:
        return render_template('combo/visualizer.html',
                               combo_str='', raw_combo='')


# Route that handles the deletion of saved combos
@combo.route('/delete/<int:id>')
@login_required
def delete(id):
    fav = Favourite.query.filter_by(fid=id).first()
    if fav:
        db.session.delete(fav)
        db.session.commit()
        flash('You have successfuly removed the combo from your list.', 'success')
    else:
        flash('This combo does not exist.', 'danger')
    return redirect(url_for('combo.favourite'))


@combo.route('/favourite', methods=['GET', 'POST'])
@login_required
def favourite():
    uid = current_user.get_id()
    if request.method == 'POST':
        combo = request.form.get('combo_string')
        if len(combo) > 2:
            # Add combo to db with user id
            check_combo = Combo.query.filter_by(notation=combo).first()

            # Add new combo to the DB
            if not check_combo:
                # Combo does not exist
                combo_str = request.form.get('combo_str')

                # Clean the combo string
                cleaned_string = combo_str.strip("[]").strip('"')
                combo_list = ast.literal_eval(cleaned_string)

                # Buttons that spend drive bars
                drive_1 = ['DI', 'DR']
                drive_2 = ['PP', 'KK', 'PPP', 'KKK']
                drive = 0

                # Bars would have other purpose, now it should be a boolean but I haven't change the Combo model, maybe later...
                bars = '0'

                # Check input validity and calculate the use of drive bars and supers
                for btn in combo_list:
                    if btn == 'unknown':
                        flash('Cannot save combos with \'unknown\' inputs', 'warning')
                        return redirect(url_for('combo.visualizer'))
                    if btn in ['qcb2', 'qcf2', 'charge_back_forward_back_forward', 'demon']:
                        bars = '1'
                    if btn in drive_1:
                        drive += 1
                    elif btn in drive_2:
                        drive += 2
                    elif btn == 'DRC':
                        drive += 3

                # Add combo do DB
                new_combo = Combo(notation=combo, drive=str(drive), bars=bars)

                db.session.add(new_combo)
                db.session.commit()

            # Add combo to user's favourites
            cid = Combo.query.filter_by(notation=combo).first().cid

            favourite = Favourite.query.filter_by(cid=cid, uid=uid).first()
            if favourite:
                flash('You already have saved this combo', 'warning')
                return redirect(url_for('combo.visualizer'))

            new_fav = Favourite(cid=cid, uid=uid)

            db.session.add(new_fav)
            db.session.commit()
            flash('You have saved the combo to your favourites.', 'success')
        else:
            flash('Please input a combo.', 'info')
        return redirect(url_for('combo.visualizer'))
    elif request.method == 'GET':
        favourites = Favourite.query.filter_by(uid=uid).all()
        ids = [fav.fid for fav in favourites]
        fav_combos = [Combo.query.filter_by(cid=fav.cid).first() for fav in favourites]
        for combo in fav_combos:
            combo.notation = convert_combo(combo.notation).split(' ')

        combo_list = list(zip(ids, fav_combos))

        return render_template('combo/favourite.html', favourites=combo_list)

combovis/blueprints/core/routes.py
from flask import render_template, Blueprint

core = Blueprint('core', __name__, template_folder='templates')


@core.route('/')
def index():
    return render_template('core/index.html')

combovis/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block styles %}
        {{ bootstrap.load_css() }}
        <link rel="stylesheet" href="/static/css/styles.css">
    {% endblock %}
    <title>{% block title %}{% endblock %} | Combo Visualizer</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <a href="{{ url_for('core.index') }}" class="navbar-brand"><img src="../static/img/Punch.png" alt="LOGO" width="12%"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto w-100">
                    <li class="nav-item mx-lg-auto">
                        <a href="{{ url_for('combo.visualizer') }}" class="nav-link">Visualize combo</a>
                    </li>
                    <li class="nav-item mx-lg-auto">
                        <a href="{{ url_for('combo.favourite')}}" class="nav-link">Saved combos</a>
                    </li>

                    <li class="nav-item ms-lg-auto"></li>
                    <li class="nav-item ms-lg-auto"></li>

                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.login') }}" class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.register') }}" class="nav-link">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
    {% block content %}{% endblock %}

    {% block scripts %}    
        {{ bootstrap.load_js() }}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="../static/js/index.js"></script>
    {% endblock %}
</body>
</html>