combovis/blueprints/combo/models.py
from combovis.app import db


class Combo(db.Model):
    # Table for the combos saved by the user
    __tablename__ = 'Combo'

    cid = db.Column(db.Integer, primary_key=True)
    notation = db.Column(db.String(), unique=True, nullable=False)
    drive = db.Column(db.String(), nullable=False)
    bars = db.Column(db.String(), nullable=False)


class Favourite(db.Model):
    # Intersection table between User and Combo (many-to-many)
    __tablename__ = 'Favourite'

    fid = db.Column(db.Integer, primary_key=True)
    cid = db.Column(db.Integer, db.ForeignKey('Combo.cid'))
    uid = db.Column(db.Integer, db.ForeignKey('users.uid'))

combovis/blueprints/combo/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from flask_login import login_required, current_user
from combovis.app import db
from .models import Combo, Favourite
import ast

from .combo_reader import convert_combo

combo = Blueprint('combo', __name__, static_folder='static', template_folder='templates')


# Route that handles combo visualization
@combo.route('/visualizer', methods=['GET', 'POST'])
def visualizer():
    if request.method == 'POST':
        form_combo = request.form.get('combo_string')
        form_combo_upper = form_combo.upper()
        converted_combo = convert_combo(form_combo_upper).split(' ')
        return render_template('combo/visualizer.html',
                               combo_str=converted_combo, raw_combo=form_combo)
    else:
        return render_template('combo/visualizer.html',
                               combo_str='', raw_combo='')


# Route that handles the deletion of saved combos
@combo.route('/delete/<int:id>')
@login_required
def delete(id):
    fav = Favourite.query.filter_by(fid=id).first()
    if fav:
        db.session.delete(fav)
        db.session.commit()
        flash('You have successfuly removed the combo from your list.', 'success')
    else:
        flash('This combo does not exist.', 'danger')
    return redirect(url_for('combo.favourite'))


@combo.route('/favourite', methods=['GET', 'POST'])
@login_required
def favourite():
    uid = current_user.get_id()
    if request.method == 'POST':
        combo = request.form.get('combo_string')
        if len(combo) > 2:
            # Add combo to db with user id
            check_combo = Combo.query.filter_by(notation=combo).first()

            # Add new combo to the DB
            if not check_combo:
                # Combo does not exist
                combo_str = request.form.get('combo_str')

                # Clean the combo string
                cleaned_string = combo_str.strip("[]").strip('"')
                combo_list = ast.literal_eval(cleaned_string)

                # Buttons that spend drive bars
                drive_1 = ['DI', 'DR']
                drive_2 = ['PP', 'KK', 'PPP', 'KKK']
                drive = 0

                # Bars would have other purpose, now it should be a boolean but I haven't change the Combo model, maybe later...
                bars = '0'

                # Check input validity and calculate the use of drive bars and supers
                for btn in combo_list:
                    if btn == 'unknown':
                        flash('Cannot save combos with \'unknown\' inputs', 'warning')
                        return redirect(url_for('combo.visualizer'))
                    if btn in ['qcb2', 'qcf2', 'charge_back_forward_back_forward', 'demon']:
                        bars = '1'
                    if btn in drive_1:
                        drive += 1
                    elif btn in drive_2:
                        drive += 2
                    elif btn == 'DRC':
                        drive += 3

                # Add combo do DB
                new_combo = Combo(notation=combo, drive=str(drive), bars=bars)

                db.session.add(new_combo)
                db.session.commit()

            # Add combo to user's favourites
            cid = Combo.query.filter_by(notation=combo).first().cid

            favourite = Favourite.query.filter_by(cid=cid, uid=uid).first()
            if favourite:
                flash('You already have saved this combo', 'warning')
                return redirect(url_for('combo.visualizer'))

            new_fav = Favourite(cid=cid, uid=uid)

            db.session.add(new_fav)
            db.session.commit()
            flash('You have saved the combo to your favourites.', 'success')
        else:
            flash('Please input a combo.', 'info')
        return redirect(url_for('combo.visualizer'))
    elif request.method == 'GET':
        favourites = Favourite.query.filter_by(uid=uid).all()
        ids = [fav.fid for fav in favourites]
        fav_combos = [Combo.query.filter_by(cid=fav.cid).first() for fav in favourites]
        for combo in fav_combos:
            combo.notation = convert_combo(combo.notation).split(' ')

        combo_list = list(zip(ids, fav_combos))

        return render_template('combo/favourite.html', favourites=combo_list)

combovis/blueprints/combo/templates/combo/favourite.html
{% extends 'base.html' %}

{% block title %}Favourites{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="./static/css/styles.css">
{% endblock %}

{% block content %}
<div class="container mt-5">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class=" alert alert-{{ category }}" id="hideMe" role="alert">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <h1 class="text-center">Favourite Combos</h1>
    {% if favourites %}
    <table class="table table-light table-striped table-bordered table-hover align-middle my-4" id="favouritesTable">
        <thead>
            <tr>
                <th scope="col" class="text-center">Combo</th>
                <th scope="col" class="text-nowrap">Drive Bars<span class="sort-arrow"></span></th>
                <th scope="col" class="text-nowrap">Super<span class="sort-arrow"></span></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for combo in favourites %}
            <tr>
                <td>
                    {% for str in combo[1].notation %}
                    {% if str == 'crouching' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button">
                    {% elif str == 'chain' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button" style="width: 3%;">
                    {% elif str == 'fwd_diag_down' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-45deg);">
                    {% elif str == 'jumping' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(180deg); margin-left: -1%;">
                    {% elif str == 'standing' %}
                    {% elif str == 'back' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(90deg);">
                    {% elif str == 'forward' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-90deg);">
                    {% elif str == 'down_down' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="margin-left: -2%;">
                    {% elif str == 'fwd_dash' %}
                        <img src="./static/img/{{ str }}.png" alt="hold_down" class="button" style="width: 7%; margin-right: -1.5%;">
                    {% elif str == 'back_dash' %}
                        <img src="./static/img/fwd_dash.png" alt="hold_down" class="button" style="width: 7%; margin-right: -1%; transform: scaleX(-1);">
                    {% elif str == 'throw' %}
                        <img src="./static/img/LightPunch.png" alt="{{ str }}" width="4.7%">
                        <img src="./static/img/LightKick.png" alt="{{ str }}" width="4.7%">
                    {% elif str == 'qcb' %}
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                    {% elif str == 'qcb2' %}
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                    {% elif str == 'qcf' %}
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button">
                    {% elif str == 'qcf2' %}
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button">
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button">
                    {% elif str == 'hcb' %}
                        <img src="./static/img/hcf.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                    {% elif str == 'hcf' %}
                        <img src="./static/img/hcf.png" alt="{{ str }}" class="button">
                    {% elif str == 'spd' %}
                        <img src="./static/img/spd.png" alt="{{ str }}" class="button">
                    {% elif str == 'double_spd' %}
                        <img src="./static/img/spd.png" alt="{{ str }}" class="button">
                        <img src="./static/img/spd.png" alt="{{ str }}" class="button">
                    {% elif str == 'reverse_dp' %}
                        <img src="./static/img/dp.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                    {% elif str == 'link' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button" style="width: 3%; margin-right: -1.25%;">
                    {% elif str == 'cancel' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button" style="width: 2%; margin-right: -0.4%;">
                    {% elif str == 'charge_down_up' %}
                        <img src="./static/img/charge_down.png" alt="{{ str }}" class="button" style="margin-right: 0%;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(180deg); margin-left: -1.25%;">            
                    {% elif str == 'charge_back_forward' %}
                        <img src="./static/img/charge_back.png" alt="{{ str }}" class="button" style="margin-right: 0;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-90deg); margin-left: 0;">
                    {% elif str == 'charge_back_forward_back_forward' %}
                        <img src="./static/img/charge_back.png" alt="{{ str }}" class="button" style="margin-right: 0;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-90deg); margin-left: 0;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(90deg); margin-left: 0;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-90deg); margin-left: 0;">
                    {% elif str == 'DRC' or str == 'DR' %}
                        <img src="./static/img/DR.png" alt="drive_rush" class="button" style="margin-right: -0.5%;">
                    {% elif str == 'PC' or str == 'CH' %}
                        <img src="./static/img/{{ str }}.png" alt="drive_rush" class="button" style="width: 12%; margin-top: 0.45%; margin-left: -0.7%; margin-right: -1%;">
                    {% elif str =='DI' %}
                        <img src="./static/img/DI.png" alt="drive_rush" class="button" style="margin-right: -1.2%;">
                    {% elif str == 'demon' %}
                        <img src="./static/img/LightPunch.png" alt="{{ str }}" class="button">
                        <img src="./static/img/Chain.png" alt="{{ str }}" class="button" style="width: 3%;">
                        <img src="./static/img/LightPunch.png" alt="{{ str }}" class="button">
                        <img src="./static/img/Chain.png" alt="{{ str }}" class="button" style="width: 3%;">
                        <img src="./static/img/crouching.png" alt="{{ str }}" class="button" style="transform: rotate(-90deg);">
                        <img src="./static/img/LightKick.png" alt="{{ str }}" class="button">
                        <img src="./static/img/Chain.png" alt="{{ str }}" class="button" style="width: 3%;">
                        <img src="./static/img/HeavyPunch.png" alt="{{ str }}" class="button">
                    {% elif str == 'PP' or str == 'KK' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" width="7%">
                    {% elif str == 'PPP' or str == 'KKK' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" width="9%">
                    {% else %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button">
                    {% endif %}
                    {% endfor %}
                </td>
                <td class="text-center">{{ combo[1].drive }}</td>
                <td class="text-center">
                    {% if combo[1].bars == '1' %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </td>
                <td>
                    <a href={{ url_for('combo.delete', id=combo[0])}}>
                        <button type="button" class="btn btn-outline-danger">Remove</button>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h3>You don't any favourite combos yet.</h3>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}    
    <script src="./static/js/sort.js"></script>
{% endblock %}

combovis/blueprints/combo/templates/combo/visualizer.html
{% extends 'base.html' %}

{% block title %}Visualizer{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="./static/css/styles.css">
{% endblock %}

{% block content %}
<div class="container mt-5">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class=" alert alert-{{ category }}" id="hideMe" role="alert">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <h1 class="text-center">Visualize Combo</h1>

    <form class="my-4" action="#" method="post">
        <div class="row">
            <div class="col-md-9">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <input type="text" name="combo_string" id="comboInput" class="form-control" placeholder="Enter combo here" required>
            </div>
            <div class="col-md-3">
                <input type="submit" class="btn btn-custom w-100" value="Visualize">
            </div>
        </div>
            
    </form>

    {% if combo_str %}
    <div class="card visualized-combo-section mb-3">
        <div class="card-body">
            <h5 class="card-title">Visualized Combo</h5>
            
                {% for str in combo_str %}
                    {% if str == 'crouching' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button">
                    {% elif str == 'chain' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button" style="width: 3%;">
                    {% elif str == 'fwd_diag_down' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-45deg);">
                    {% elif str == 'jumping' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(180deg); margin-left: -1%;">
                    {% elif str == 'standing' %}
                    {% elif str == 'back' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(90deg);">
                    {% elif str == 'forward' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-90deg);">
                    {% elif str == 'down_down' %}
                        <img src="./static/img/crouching.png" alt="hold_down" class="button">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="margin-left: -2%;">
                    {% elif str == 'fwd_dash' %}
                        <img src="./static/img/{{ str }}.png" alt="hold_down" class="button" style="width: 7%; margin-right: -1.5%;">
                    {% elif str == 'back_dash' %}
                        <img src="./static/img/fwd_dash.png" alt="hold_down" class="button" style="width: 7%; margin-right: -1%; transform: scaleX(-1);">
                    {% elif str == 'throw' %}
                        <img src="./static/img/LightPunch.png" alt="{{ str }}" width="4.7%">
                        <img src="./static/img/LightKick.png" alt="{{ str }}" width="4.7%">
                    {% elif str == 'qcb' %}
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                    {% elif str == 'qcb2' %}
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                    {% elif str == 'qcf' %}
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button">
                    {% elif str == 'qcf2' %}
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button">
                        <img src="./static/img/qcf.png" alt="{{ str }}" class="button">
                    {% elif str == 'hcb' %}
                        <img src="./static/img/hcf.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                    {% elif str == 'hcf' %}
                        <img src="./static/img/hcf.png" alt="{{ str }}" class="button">
                    {% elif str == 'spd' %}
                        <img src="./static/img/spd.png" alt="{{ str }}" class="button">
                    {% elif str == 'double_spd' %}
                        <img src="./static/img/spd.png" alt="{{ str }}" class="button">
                        <img src="./static/img/spd.png" alt="{{ str }}" class="button">
                    {% elif str == 'reverse_dp' %}
                        <img src="./static/img/dp.png" alt="{{ str }}" class="button" style="transform: scaleX(-1);">
                    {% elif str == 'link' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button" style="width: 3%; margin-right: -1.25%;">
                    {% elif str == 'cancel' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button" style="width: 2%; margin-right: -0.4%;">
                    {% elif str == 'charge_down_up' %}
                        <img src="./static/img/charge_down.png" alt="{{ str }}" class="button" style="margin-right: 0%;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(180deg); margin-left: -1.25%;">            
                    {% elif str == 'charge_back_forward' %}
                        <img src="./static/img/charge_back.png" alt="{{ str }}" class="button" style="margin-right: 0;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-90deg); margin-left: 0;">
                    {% elif str == 'charge_back_forward_back_forward' %}
                        <img src="./static/img/charge_back.png" alt="{{ str }}" class="button" style="margin-right: 0;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-90deg); margin-left: 0;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(90deg); margin-left: 0;">
                        <img src="./static/img/crouching.png" alt="hold_down" class="button" style="transform: rotate(-90deg); margin-left: 0;">
                    {% elif str == 'DRC' or str == 'DR' %}
                        <img src="./static/img/DR.png" alt="drive_rush" class="button" style="margin-right: -0.5%;">
                    {% elif str == 'PC' or str == 'CH' %}
                        <img src="./static/img/{{ str }}.png" alt="drive_rush" class="button" style="width: 12%; margin-top: 0.45%; margin-left: -0.7%; margin-right: -1%;">
                    {% elif str =='DI' %}
                        <img src="./static/img/DI.png" alt="drive_rush" class="button" style="margin-right: -1.2%;">
                    {% elif str == 'demon' %}
                        <img src="./static/img/LightPunch.png" alt="{{ str }}" class="button">
                        <img src="./static/img/Chain.png" alt="{{ str }}" class="button" style="width: 3%;">
                        <img src="./static/img/LightPunch.png" alt="{{ str }}" class="button">
                        <img src="./static/img/Chain.png" alt="{{ str }}" class="button" style="width: 3%;">
                        <img src="./static/img/crouching.png" alt="{{ str }}" class="button" style="transform: rotate(-90deg);">
                        <img src="./static/img/LightKick.png" alt="{{ str }}" class="button">
                        <img src="./static/img/Chain.png" alt="{{ str }}" class="button" style="width: 3%;">
                        <img src="./static/img/HeavyPunch.png" alt="{{ str }}" class="button">
                    {% elif str == 'PP' or str == 'KK' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" width="7%">
                    {% elif str == 'PPP' or str == 'KKK' %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" width="9%">
                    {% else %}
                        <img src="./static/img/{{ str }}.png" alt="{{ str }}" class="button">
                    {% endif %}
                {% endfor %}    
        </div>
    <div class="text-center">
        <form action="{{ url_for('combo.favourite')}}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input type="text" name="combo_string" value="{{ raw_combo }}" hidden>
            <input type="text" name="combo_str" value="{{ combo_str }}" hidden>
            <input type="submit" class="btn btn-success w-25" value="Save combo!">
        </form>
    </div>
    </div>
    {% endif %}

    <h2 class="text-center mt-5">
        <a class="btn btn-secondary w-100" data-bs-toggle="collapse" href="#notationTable" role="button" aria-expanded="false" aria-controls="notationTable">
          Notation Guide
        </a>
    </h2>
    <div class="collapse" id="notationTable">
        <div class="table-responsive mt-3">
            <table class="table table-striped table-bordered">
                <!-- <thead class="thead-dark">
                    <tr>
                        <th scope="col">Button</th>
                        <th scope="col">Explanation</th>
                    </tr>
                </thead> -->
                <tbody>
                    <tr>
                        <td><img src="./static/img/LightPunch.png" alt="{{ str }}" class="img-fluid" width="50"><img src="./static/img/LightKick.png" alt="{{ str }}" class="img-fluid" width="50"></td>
                        <td>Blue buttons represent Light attacks</td>
                    </tr>
                    <tr>
                        <td><img src="./static/img/MediumPunch.png" alt="{{ str }}" class="img-fluid" width="50"><img src="./static/img/MediumKick.png" alt="{{ str }}" class="img-fluid" width="50"></td>
                        <td>Yellow buttons represent Medium attacks</td>
                    </tr>
                    <tr>
                        <td><img src="./static/img/HeavyPunch.png" alt="{{ str }}" class="img-fluid" width="50"><img src="./static/img/HeavyKick.png" alt="{{ str }}" class="img-fluid" width="50"></td>
                        <td>Red buttons represent Heavy attacks</td>
                    </tr>
                    <tr>
                        <td><img src="./static/img/Punch.png" alt="{{ str }}" class="img-fluid" width="50"><img src="./static/img/Kick.png" alt="{{ str }}" class="img-fluid" width="50"></td>
                        <td>Grey buttons represent any kind of Punch/Kick</td>
                    </tr>
                    <tr>
                        <td><img src="./static/img/Link.png" alt="" class="img-fluid" width="50"></td>
                        <td>Link: input the next button after the <b>complete</b> animation of the previous move</td>
                    </tr>
                    <tr>
                        <td><img src="./static/img/Chain.png" alt="" class="img-fluid" width="50"></td>
                        <td>Chain: input the next button in the combo</td>
                    </tr>
                    <tr>
                        <td><img src="./static/img/Cancel.png" alt="" class="img-fluid" width="50"></td>
                        <td>Cancel: cancel the previous input into the next</td>
                    </tr>
                    <tr>
                        <td><img src="./static/img/DI.png" alt="" class="img-fluid" width="50"></td>
                        <td>Drive Impact: HP + HK</td>
                    </tr>
                    <tr>
                        <td><img src="./static/img/DR.png" alt="" class="img-fluid" width="50"></td>
                        <td>Drive Rush: dash during parry or dash/MP+MK after a DR-cancelable move</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
    
{% endblock %}